language: go
go: 1.4
python: 2.7
jdk: oraclejdk8

before_install:
  - mkdir -p $HOME/gopath/src/sourcegraph.com/sourcegraph
  - mv $TRAVIS_BUILD_DIR $HOME/gopath/src/sourcegraph.com/sourcegraph/srclib
  - export TRAVIS_BUILD_DIR=$HOME/gopath/src/sourcegraph.com/sourcegraph/srclib
  # for rst2html (package doc)
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-docutils
  - export PATH=$PATH:$HOME/gopath/bin
  - export GOBIN=$HOME/gopath/bin
  - sudo pip install virtualenv

install:
  - go get -d -v ./... && go build -v ./...
  - go install ./cmd/srclib

before_script:
  # gradle
  - wget https://services.gradle.org/distributions/gradle-2.6-bin.zip
  - unzip gradle-2.6-bin.zip -d $PWD
  - rm gradle-2.6-bin.zip
  - chmod u+x $PWD/gradle-2.6/bin/gradle
  - sudo ln -s $PWD/gradle-2.6/bin/gradle /usr/bin/gradle

script:
  - go test -v ./...
  - make install-std-toolchains
  - make test-std-toolchains

