// Code generated by protoc-gen-gogo.
// source: toolref.proto
// DO NOT EDIT!

/*
Package srclib is a generated protocol buffer package.

It is generated from these files:
	toolref.proto

It has these top-level messages:
	ToolRef
*/
package srclib

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// discarding unused import gogoproto "github.com/gogo/protobuf/gogoproto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// A ToolRef identifies a tool inside a specific toolchain. It can be
// used to look up the tool.
type ToolRef struct {
	// Toolchain is the toolchain path of the toolchain that contains this tool.
	Toolchain string `protobuf:"bytes,1,opt,name=toolchain,proto3" json:"toolchain,omitempty"`
	// Subcmd is the name of the toolchain subcommand that runs this tool.
	Subcmd string `protobuf:"bytes,2,opt,name=subcmd,proto3" json:"subcmd,omitempty"`
}

func (m *ToolRef) Reset()         { *m = ToolRef{} }
func (m *ToolRef) String() string { return proto.CompactTextString(m) }
func (*ToolRef) ProtoMessage()    {}
